apiVersion: argoproj.io/v1alpha1
#apiVersion: argoproj.io/v1beta1
kind: Application
metadata:
  name: myapp-argo-application
  #namespace: argocd
  namespace: myargo
spec:
  project: default

  source:
    repoURL: https://github.com/SathyajithPuttaiah/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    #server: https://kubernetes.default.svc
    #server: https://arn:aws:eks:ap-south-1:225992052696:cluster/child1
    server: https://3895F26E304C4CE527BCA3E40EEDC52F.gr7.ap-south-1.eks.amazonaws.com
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true